### ISSUE TITLE
Will you marry me?

### ISSUE THREAD

**Issue by robdyke** [denisetyk/Space2#1]
I want to play Space Invaders with you for the rest of my days

**Comment by denisetyk** [comment]
I want your pull requests and issues.

**Comment by robdyke** [comment]
Let's take this offline

**Comment by aderowbotham** [comment]
OMG amazing and congratulations! 🎊

**Comment by sickcodes** [comment]
Congratulations, good first issue. Can confirm this issue was resolved 23rd September 2023!

**Comment by microhobby** [comment]
LGTM

**Comment by BeeHiveSafety** [comment]
Congratulations <3

**Comment by jothi-prasath** [comment]
I think the issue is resolved

**Comment by robdyke** [comment]
Fixed 22 September 2023

**Comment by spmedia** [comment]
This is beautiful

**Comment by ryanwinchester** [comment]
When is the merge date?

**Comment by Demkeys** [comment]
Congrats!

**Comment by Rafalski** [comment]
Approved.
